services:
  web:
    build: ./docker/php
    container_name: fastdungeon_web
    ports:
      - "8000:80"
    volumes:
      - ./symfony:/var/www/html
    depends_on:
      - database

  database:
    image: mariadb:11
    container_name: fastdungeon_db
    environment:
      MARIADB_DATABASE: fastdungeon
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfypass
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
